sonar.projectKey=leon36000_ForgeAI-Toolkit
sonar.organization=leon36000

sonar.sources=src,scripts
sonar.tests=tests
sonar.exclusions=**/__pycache__/**,**/*.pyc,src/forgeai/data/**
sonar.test.exclusions=**/__pycache__/**,**/*.pyc

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.12
sonar.sourceEncoding=UTF-8
